sudo: true
language: elixir
elixir:
  - 1.7.3
otp_release:
  - 21.0
matrix:
  include:
    - elixir: 1.7.3
      otp_release: 21.0
script:
  - mix analyze --non-interactive
after_success:
  - MIX_ENV=test mix coveralls.travis
cache:
  directories:
    - _build
    - deps
