sudo: true
language: elixir
elixir:
  - 1.10.2
otp_release:
  - 22.2
matrix:
  include:
    - elixir: 1.10.2
      otp_release: 22.2
script:
  - mix analyze --non-interactive
after_success:
  - MIX_ENV=test mix coveralls.travis
cache:
  directories:
    - _build
    - deps
